name: Create Release on Push or Pull Request

# Триггеры: запуск при пуше в main или при принятии PR в main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаут репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Настройка JDK для Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Делаем gradlew исполняемым
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Сборка релизного APK
      - name: Build Release APK
        env:
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      # 6. Получение версии из build.gradle.kts для тега релиза
      - name: Get version name
        id: version
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk '{print $3}' | tr -d '"')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT

      # 7. Создание релиза в GitHub
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION_NAME }}
          release_name: Release v${{ steps.version.outputs.VERSION_NAME }}
          draft: false
          prerelease: false

      # 8. Загрузка APK в релиз как артефакт
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release-v${{ steps.version.outputs.VERSION_NAME }}.apk
          asset_content_type: application/vnd.android.package-archive