name: Create Release on Push or Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаут репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Настройка JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Делаем gradlew исполняемым
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Создание временной папки для keystore
      - name: Create temp directory for keystore
        run: mkdir -p app/temp_keys

      # 5. Сохранение Base64 секрета
      - name: Save Keystore Base64
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.base64
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # 6. Декодирование keystore
      - name: Decode Keystore
        run: base64 -d keystore.base64 > app/temp_keys/key.jks

      # 7. Проверка наличия keystore
      - name: Check Keystore File
        run: ls -la app/temp_keys/

      # 8. Сборка релизного APK
      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
            -PKEYSTORE_PATH=app/temp_keys/key.jks \
            -PKEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
            -PKEY_ALIAS="${{ secrets.KEY_ALIAS }}" \
            -PKEY_PASSWORD="${{ secrets.KEY_PASSWORD }}" \
            --info

      # 9. Установка Android SDK, Build Tools и Platform Tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-tools-version: '36.0.0'  # Версия Build Tools
      - name: Install Android Build Tools and Platform Tools
        run: |
          yes | sdkmanager "build-tools;36.0.0" "platform-tools"
          echo "ANDROID_HOME=$ANDROID_HOME"  # Для отладки
          echo "PATH=$PATH"  # Для отладки
      - name: Verify apksigner
        run: which apksigner  # Проверка доступности apksigner

      # 10. Подпись APK с временной меткой
      - name: Sign APK with timestamp
        run: |
          apksigner sign \
          --ks app/temp_keys/key.jks \
          --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --ks-key-alias ${{ secrets.KEY_ALIAS }} \
          --tsa http://timestamp.digicert.com \
          app/build/outputs/apk/release/app-release.apk

      # 11. Получение версии из build.gradle.kts для тега релиза
      - name: Get version name
        id: version
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk '{print $3}' | tr -d '"')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT

      # 12. Создание релиза в GitHub
      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION_NAME }}
          release_name: Release v${{ steps.version.outputs.VERSION_NAME }}
          draft: false
          prerelease: false

      # 13. Загрузка APK в релиз как артефакт
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release-v${{ steps.version.outputs.VERSION_NAME }}.apk
          asset_content_type: application/vnd.android.package-archive

      # 14. Очистка временных файлов
      - name: Clean up
        run: rm -f keystore.base64 app/temp_keys/key.jks
        if: always()